export enum EError {
    CANNOT_READ_TSCONFIG = 0,
    CANNOT_PARSE_TSCONFIG = 1,
    NON_EXISTS_PROJECT_PATH = 2,
    TSCONF_NOT_EXISTS = 3,
    NO_FILES_TO_ANALYZE = 4,
    MISSING_PROJECT = 5,
    MISSING_SRC_PATH = 6
}
